Core.Web/Controllers/DepartmentController.cs
using Core.Model;
using Core.Model.ViewModels;
using Core.Service;
using Core.Service.Services;
using Core.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;

namespace Core.Web.Controllers
{
    public class DepartmentController : BaseController
    {

        private IServiceWrapper _serviceWrapper;

        public DepartmentController(IOptions<MailSettings> _mailSettings, IServiceWrapper serviceWrapper, IWebHostEnvironment webHostEnvironment):base(_mailSettings,webHostEnvironment)
        {
            _serviceWrapper = serviceWrapper;
        }

      
        public IActionResult Index()
        {
            ViewBag.Departments = (List<SelectListItem>)_serviceWrapper.departmentServices.GetSelectDepartments();
            return View();
        }



        public IActionResult AddDepartment()
        {
            ViewBag.Departments = (List<SelectListItem>)_serviceWrapper.departmentServices.GetSelectDepartments();
            return View();
        }


        [HttpPost]
        public IActionResult AddDepartment(Department model)
        {
            if (ModelState.IsValid)
            {
                _serviceWrapper.departmentServices.CreateDepartment(model);
                _serviceWrapper.departmentServices.SaveDepartment();
                return RedirectToAction("AddDepartment");
            }
                return View();
        }

        public IActionResult GetDepartments(int id)
        {  
            var model = _serviceWrapper.departmentServices.GetDepartment(id);

            List<Department> ParentDepartments = GetParents(model).ToList();
            ParentDepartments.Reverse();

            ViewBag.department = model.Name;
            return PartialView("_GetDepartments",new DepartmentList { SubDepartments = GetChildern(id), model = model, ParentDepartments = ParentDepartments });
        }

        public List<Department> GetChildern(int id)
        {
          var model= _serviceWrapper.departmentServices.GetChildern(id);
            return model;
        }

        IEnumerable<Department> GetParents(Department model)
        {
            Department dParent = model.ParentDepartment;
            while (dParent != null)
            {
                yield return dParent;
                dParent = dParent.ParentDepartment;
            }
        }

  

        public JsonResult CheckExistingName(string Name, int DepartmentId)
        {
            var res = _serviceWrapper.departmentServices.CheckName(Name);
            if (res != null)
            {
                if (res.DepartmentId != DepartmentId)
                {
                    return Json(false);
                }
            }
            return Json(true);
        }


    }
}

Core.Web/Controllers/MessageController.cs
using Core.Model;
using Core.Model.ViewModels;
using Core.Service;
using Core.Web.ViewModels;
using Hangfire;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Core.Web.Controllers
{
    public class MessageController : BaseController
    {

        private IServiceWrapper _serviceWrapper;
        private IBackgroundJobClient _backgroundJobClient;
        public MessageController(IOptions<MailSettings> _mailSettings, IBackgroundJobClient backgroundJobClient, IServiceWrapper serviceWrapper, IWebHostEnvironment webHostEnvironment) : base(_mailSettings, webHostEnvironment)
        {
            _serviceWrapper = serviceWrapper;
            _backgroundJobClient = backgroundJobClient;
        }

        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public IActionResult AddMessage(Message model)
        {
            if (ModelState.IsValid)
            {
                _serviceWrapper.messageServices.CreateMessage(model);
                _serviceWrapper.messageServices.SaveMessage();

                //ToEmail set static to test only
                MailRequest request = new MailRequest { Subject = "Task-Project", ToEmail = "emanshaker381@gmail.com", Body = model.Title };

                var selectedDate = DateTimeOffset.Parse(model.SendTime.ToString("yyyy-MM-dd hh:mm:ss"));
                BackgroundJob.Schedule(() => SendMessage(request, model), selectedDate);

                return Json("1");
            }
            return Json("-1");
        }


        public async Task SendMessage(MailRequest request, Message model)
        {
            try
            {
                await _serviceWrapper.MailService.SendEmailAsync(request);
                model.IsSend = true;
            }
            catch (Exception ex)
            {
                model.IsSend = false;
            }

            _serviceWrapper.messageServices.UpdateMessage(model);
            _serviceWrapper.messageServices.SaveMessage();
        }


        public IActionResult GetMessages()
        {
            return PartialView("_MessageList", _serviceWrapper.messageServices.GetMessages().OrderBy(x => x.SendTime).ToList());
        }
    }
}

Core.Web/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="icon" href="favicon.ico" type="image/x-icon" />

    <title>Task Project</title>

    <!-- Bootstrap Core and vandor -->
    <link rel="stylesheet" href="~/plugins/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/plugins/dropify/css/dropify.min.css">

    <!-- Core css -->
    <link rel="stylesheet" href="~/css/main.css" />
    <link rel="stylesheet" href="~/css/theme1.css" />

    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/fontawesome.css" />
    <style>
          .input-validation-error {
            border: 1px dashed red !important;
        }

    </style>
</head>

<body class="font-montserrat">

    <!-- Overlay For Sidebars -->

    <div id="main_content">

        <div id="header_top" class="header_top">
            <div class="container">
                <div class="hleft">
                    <a class="header-brand"><i class="brand-logo"></i></a>
                    <div class="dropdown">
                    </div>
                </div>

            </div>
        </div>

        <div id="left-sidebar" class="sidebar ">
            <h5 class="brand-name">Task  </h5>
            <nav id="left-sidebar-nav" class="sidebar-nav">
                <ul class="metismenu">

                    <li><a asp-action="Index" asp-controller="Department"><span>Departments</span></a></li>
                    <li><a asp-action="AddDepartment" asp-controller="Department"><span>Add Department</span></a></li>
                    <li><a asp-action="Index" asp-controller="Message"><span> Reminder</span></a></li>

                </ul>
            </nav>
        </div>
        <div class="page">
            @RenderBody()
        </div>

    </div>


    <script src="~/bundles/lib.vendor.bundle.js"></script>

    <script src="~/plugins/dropify/js/dropify.min.js"></script>

    <script src="~/js/core.js"></script>
    <script src="~/js/fontawesome.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
      <partial name="_Validation" />
    @RenderSection("Scripts", required: false)
</body>

</html>

Core.Web/Views/Shared/_Validation.cshtml
<script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js" asp-append-version="true"></script>